### ISSUE TITLE
GestureManager not working in SDK 3.2.0(-beta.2)

### ISSUE THREAD

**Issue by JustBuddy** [BlackStartx/VRC-Gesture-Manager#21]
Packages\vrchat.blackstartx.gesture-manager\Scripts\Editor\Modules\Vrc3\AvatarDynamics\AvatarDynamicReset.cs(44,30): error CS0246: The type or namespace name 'PhysBoneGrabHelper' could not be found (are you missing a using directive or an assembly reference?)

**Comment by PinballsWizard** [comment]
This issue has knock on effects of other tools, such as VRCFury which will not install while this error is occurring.

**Comment by BlackStartx** [comment]
Hi, sorry for the issues~ ♥

This is now fixed in version 3.8.4!
###### P.S: Right now is downloadable as a pre-release~ ;3
